### ISSUE TITLE
Router is not working properly with the ng-grid

### ISSUE THREAD

**Issue by rohan-jha** [angular-ui/ui-grid#1238]
Team,

I am trying to navigate to the different route based on the user click event triggered from the ng-grid row and getting an exception which is hampering the route execution.

Following is my code:

$scope.topicGridOptions = { 
  data: 'topics',  
  columnDefs: [{field:'topicId', displayName:'Topic ID'},  
                        {field:'topicName', displayName:'Topic Name'},  
                        {field:'topicURL', displayName:'Topic URL'},
                        {field:'topicMessages', displayName:'View Messages', 
                             cellTemplate:'Here I am showing a div which on ng-dblclick triggers showMsg'}
                        ]
};

$scope.showMsg= function(rowObj){
            $scope.messages = rowObj.entity.topicMessages;
            $location.path('/message');
};

And when showMsg is getting called I am getting the following error:

TypeError: Cannot read property 'off' of null
    at HTMLDivElement.<anonymous> (http://localhost:63342/angularSkeleton/app/lib/angularUI/js/ng-grid-2.0.11.debug.js:1008:31)
    at HTMLDivElement.p.event.dispatch (http://localhost:63342/angularSkeleton/app/lib/jquery/jquery-1.8.0.js:1:37944)
    at HTMLDivElement.g.handle.h (http://localhost:63342/angularSkeleton/app/lib/jquery/jquery-1.8.0.js:1:33888)
    at Object.p.event.trigger (http://localhost:63342/angularSkeleton/app/lib/jquery/jquery-1.8.0.js:1:36564)
    at p.fn.extend.triggerHandler (http://localhost:63342/angularSkeleton/app/lib/jquery/jquery-1.8.0.js:1:44409)
    at removePatch [as remove](http://localhost:63342/angularSkeleton/app/lib/angular/angular.js:2099:21)
    at Object.leave (http://localhost:63342/angularSkeleton/app/lib/angular/angular.js:3893:17)
    at cleanupLastView (http://localhost:63342/angularSkeleton/app/lib/angular/angular-route.js:834:22)
    at update (http://localhost:63342/angularSkeleton/app/lib/angular/angular-route.js:861:13)
    at Scope.$broadcast (http://localhost:63342/angularSkeleton/app/lib/angular/angular.js:11909:28) angular.js:9159
(anonymous function) angular.js:9159
(anonymous function) angular.js:6751
Scope.$broadcast angular.js:11911
(anonymous function) angular-route.js:556
wrappedCallback angular.js:10655
wrappedCallback angular.js:10655
(anonymous function) angular.js:10741
Scope.$eval angular.js:11634
Scope.$digest angular.js:11479
Scope.$apply angular.js:11740
done angular.js:7744
completeRequest angular.js:7918
xhr.onreadystatechange

**Comment by SagarBaggaOutlook** [comment]
I am facing the same issue and looking forward to get any kinda help outside here.

**Comment by SagarBaggaOutlook** [comment]
ui-grid.info/docs/#/tutorial/305_appScope
