### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by Pitel** [angular-ui/ui-grid#1393]
Both example grid on home page and tutorial example http://ui-grid.info/docs/#/tutorial/102_sorting does not work. Clicking on grid hgeader changes the caret, but the content of the table remains the same.

Chrome 38-dev. This appears in console:

```
Error: No sorting function found for type:undefined
    at Object.guessSortFn (http://ui-grid.info/release/ui-grid-unstable.js:5985:15)
    at Object.getSortFn (http://ui-grid.info/release/ui-grid-unstable.js:6088:26)
    at rowSortFn (http://ui-grid.info/release/ui-grid-unstable.js:6175:28)
    at Array.sort (native)
    at Object.rowSorterSort [as sort] (http://ui-grid.info/release/ui-grid-unstable.js:6165:17)
    at Grid.sortByColumn (http://ui-grid.info/release/ui-grid-unstable.js:3944:22)
    at startProcessor (http://ui-grid.info/release/ui-grid-unstable.js:3526:33)
    at handleProcessedRows (http://ui-grid.info/release/ui-grid-unstable.js:3542:20)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.js:11046:81)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.js:11046:81) angular.js:9509(anonymous function) angular.js:9509(anonymous function) angular.js:6950wrappedCallback angular.js:11049wrappedCallback angular.js:11046(anonymous function) angular.js:11132Scope.$eval angular.js:12075Scope.$digest angular.js:11903(anonymous function) angular.js:12113completeOutstandingRequest angular.js:4193(anonymous function) angular.js:4494
```

**Comment by aharonkoss** [comment]
Actually there is no issue here. After reviewing the Grid Options API (http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef), all columns are assumed alpha numeric unless you set the "type" property to number or numberStr. See example below:
{ name: "timeInStage", displayName: 'Time in Stage', enableSorting: true, headerCellClass: 'mpncustomheader', width: 120, cellClass: 'mpncenter', type: 'number', cellTooltip: true }
