### ISSUE TITLE
sorting still not working even when using stable

### ISSUE THREAD

**Issue by c0debreaker** [angular-ui/ui-grid#2437]
Hi folks,

I've read this and tried https://github.com/angular-ui/ng-grid/issues/1393 but it's still not working for me.
I'm now pointing to http://ui-grid.info/release/ui-grid-unstable.js but I'm still getting the error below when I click on the header fields. I'm not sure if I need to modify my code other than pointing to the latest build. I also posted a question to stackoverflow in case someone has encountered it.

http://stackoverflow.com/questions/27642418/angular-ui-grid-sorting-failing?noredirect=1#comment43703691_27642418

Error: No sorting function found for type:undefined
    at Object.guessSortFn (http://ui-grid.info/release/ui-grid-unstable.js:8162:15)
    at Object.getSortFn (http://ui-grid.info/release/ui-grid-unstable.js:8406:26)
    at rowSortFn (http://ui-grid.info/release/ui-grid-unstable.js:8532:28)
    at Array.sort (native)
    at Object.rowSorterSort [as sort](http://ui-grid.info/release/ui-grid-unstable.js:8522:17)
    at Grid.sortByColumn (http://ui-grid.info/release/ui-grid-unstable.js:4777:22)
    at startProcessor (http://ui-grid.info/release/ui-grid-unstable.js:4376:33)
    at handleProcessedRows (http://ui-grid.info/release/ui-grid-unstable.js:4392:20)
    at l.promise.then.L (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js:99:469)
    at l.promise.then.L (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js:99:469)

**Comment by aharonkoss** [comment]
If you where having the same issue I was the numeric sorting wasn't working. You have to define your column type as a number or numberStr. The sorting will work as expected. This is in the UI Grid API documentation (http://ui-grid.info/docs/#/tutorial/307_external_sorting). See below example:
{ name: "timeInStage", displayName: 'Time in Stage', enableSorting: true, headerCellClass: 'mpncustomheader', width: 120, cellClass: 'mpncenter', type: 'number', cellTooltip: true }

**Comment by UnnamedSong** [comment]
@aharonkoss 
Thank you very much.
*type: 'number'*
It works well.
