### ISSUE TITLE
UI grid pdf exporter is not working in IE

### ISSUE THREAD

**Issue by kushalt** [angular-ui/ui-grid#3991]
I have IE 10 version and getting following error when trying to export data in .pdf

TypeError: Object doesn't support property or method 'defineGetter'

Any help would be greatly appreciated.

**Comment by JLLeitschuh** [comment]
Do you have a specific line/stack trace indicating where this error is coming from?
We need more information to help you.
Related: #2921

**Comment by kushalt** [comment]
It gives following stack trace in console.

TypeError: Object doesn't support property or method '__defineGetter__'
   at FontWrapper (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:14169:4)
   at provideFont (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:2269:4)
   at Anonymous function (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:16130:4)
   at measure (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:16118:3)
   at buildInlines (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:15941:3)
   at measureLeaf (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:14557:3)
   at Anonymous function (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:14437:5)
   at auto (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:16306:3)
   at measureNode (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:14422:3)
   at Anonymous function (http://ui-grid.info/docs/grunt-scripts/pdfmake.js:14709:5)

**Comment by PaulL1** [comment]
That looks to be an upstream issue in the pdfMake library.  I had thought we had some people working on IE, but it's always been a bit of a pain because I don't personally have an IE instance to test against.  Are you able to use the pdfMake sandbox on IE?

**Comment by gdesigner31** [comment]
@paul ; I am facing same issue , Ui grid not working in IE10 and < versions

**Comment by PaulL1** [comment]
It's not clear to me what your problem is @gdesigner31.  I think ui-grid does work in IE10 and sort of works in IE9.  Do you mean specifically exporter?

I'm not clear why you'd be calling the downloadPDF method.  Would you not use the menu items?

**Comment by gdesigner31** [comment]
![ui-grid-issue](https://cloud.githubusercontent.com/assets/8740745/9349450/dede3b1c-4663-11e5-811e-cb9304ea470c.jpg)


We are using IE 10 version and when I click on export data as PDF ,above error will show on console.

**Comment by PaulL1** [comment]
This is an upstream issue on pdfMake, and should be logged there (and I believe it already is logged there).
