### ISSUE TITLE
Error running grunt dev

### ISSUE THREAD

**Issue by webiks** [angular-ui/ui-grid#4071]
I've tried to make the git work on my home PC. It gives an error when I run grunt dev:

C:\Users\myComputer\Documents\GitHub\ui-grid [master]> grunt dev
C:\Users\myComputer\Documents\GitHub\ui-grid\node_modules\grunt\node_modules\findup-
sync\node_modules\lodash\dist\lodash.js:1517
});
^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\myComputer\Documents\GitHub\ui-grid\node_modules
\grunt\node_modules\findup-sync\lib\findup-sync.js:16:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Any idea why?

**Comment by webiks** [comment]
Reinstalled and it now works correctly.
