### ISSUE TITLE
jquery.URI incompatibility 

### ISSUE THREAD

**Issue by paymok** [angular-ui/ui-grid#4104]
I have followed the tutorial and create a simple ui-grid in a blank page. Everything works fine except when I click the sort menu inside the column, all the sorting options become {{ name }}, looks like angular couldn't translate the variable to proper text? Am i missing anything? 

![image](https://cloud.githubusercontent.com/assets/1615590/9037125/8466dcac-3a1a-11e5-8b9d-6c0a468adbb0.png)
This is whats happening in my local project

![image](https://cloud.githubusercontent.com/assets/1615590/9037264/29869e10-3a1c-11e5-9d18-fec08eb6c0dd.png)
Suppose i should see something like this 

Also not sure if this is the root cause of causing , I am getting these error when the table loaded up. the same errors occur when i click and expand the row record.
I am using AngularJS v1.2.16, latest stable release UI-grid (3.0), Require.js to manage the dependency and disabled the angular-animate (not sure if this is related). 

<i>
Error: Element "LI" does not have either property: href, src, action, cite
    at Error (native)
    at d.fn.uri (http://localhost:8080/test-module/assets/plugins/uri/jquery.URI.min.js:6:72)
    at Object.r [as set] (http://localhost:8080/test-module/assets/plugins/uri/jquery.URI.min.js:5:329)
    at Function.n.extend.attr (http://localhost:8080/test-module/assets/plugins/jquery-1.11.0.min.js:4:10684)
    at e.attr (http://localhost:8080/test-module/assets/plugins/jquery-migrate-1.2.1.min.js:2:1892)
    at n.access (http://localhost:8080/test-module/assets/plugins/jquery-1.11.0.min.js:3:2985)
    at n.fn.extend.attr (http://localhost:8080/test-module/assets/plugins/jquery-1.11.0.min.js:4:10224)
    at Object.Hb.$set (http://localhost:8080/test-module/assets/plugins/angular/angular.min.js:64:210)
    at http://localhost:8080/test-module/assets/plugins/angular/angular.min.js:57:423
    at q (http://localhost:8080/test-module/assets/plugins/angular/angular.min.js:7:386)(anonymous function) @ assets/plugins/angular/angular.min.js:89
 </i>

**Comment by paymok** [comment]
OK i have resolved this problem. This is due to some incompatibility between jquery.uri.js and ui-grid.

In JQuery.uri.js, when any element contains attr [src', 'href', 'action', 'uri', 'cite'], it will append a hock to the element and do something else ( I didn't dig deep to see what's it is actually doing, but this is the root cause why jquery.uri.js throwing error).
![image](https://cloud.githubusercontent.com/assets/1615590/9079585/630ece1a-3b7e-11e5-84e6-3a60f3ecc44a.png)

In ui-grid, li.ui-grid-menu-item, in  $templateCache.put('ui-grid/uiGridMenu', ... 
there is a LI element which contains an action attribute, which i think this is a syntax error for html standard where li should not have action attribute and action should be a reserved attribute,  although  I understand its a directive, and you get the right to name/create whatever attribute you want to the element. 

![image](https://cloud.githubusercontent.com/assets/1615590/9079579/4f899906-3b7e-11e5-8eaf-5ba90db7ad59.png)

Anyway, jquey.uri.js mistakenly think li element action is a URI base element, and add the hook and try to do blah blah blah until it hits the problem, li shouldn't have 'action' attribute.

I think someone should make some changes in ui-grid to avoid using reserved attribute name in to create a directive element. 

In my case, after i removed the jquery.uri.js reference, everything works fine.
