### ISSUE TITLE
Failed to instantiate module {}

### ISSUE THREAD

**Issue by t638403** [angular-ui/ui-grid#4485]
When using ui.grid as a npm module I got this error in the browser:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.3.20/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at REGEX_STRING_REGEXP (http://localhost:8080/js/external.js:2209:12)
    at assertArg (http://localhost:8080/js/external.js:3737:11)
    at assertArgFn (http://localhost:8080/js/external.js:3747:3)
    at http://localhost:8080/js/external.js:6297:11
    at forEach (http://localhost:8080/js/external.js:2473:20)
    at loadModules (http://localhost:8080/js/external.js:6267:5)
    at http://localhost:8080/js/external.js:6289:40
    at forEach (http://localhost:8080/js/external.js:2473:20)
    at loadModules (http://localhost:8080/js/external.js:6267:5)
    at createInjector (http://localhost:8080/js/external.js:6188:11)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=%7B%7D&p1=Error%3A…teInjector%20(http%3A%2F%2Flocalhost%3A8080%2Fjs%2Fexternal.js%3A6188%3A11)
    at REGEX_STRING_REGEXP (http://localhost:8080/js/external.js:2209:12)
    at http://localhost:8080/js/external.js:6311:15
    at forEach (http://localhost:8080/js/external.js:2473:20)
    at loadModules (http://localhost:8080/js/external.js:6267:5)
    at http://localhost:8080/js/external.js:6289:40
    at forEach (http://localhost:8080/js/external.js:2473:20)
    at loadModules (http://localhost:8080/js/external.js:6267:5)
    at createInjector (http://localhost:8080/js/external.js:6188:11)
    at doBootstrap (http://localhost:8080/js/external.js:3602:20)
    at bootstrap (http://localhost:8080/js/external.js:3623:12)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=app&p1=Error%3A%20…0bootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Fjs%2Fexternal.js%3A3623%3A12)
```

Possible solution/workaround:

I added `module.exports = 'ui.grid'` at the end of ui.grid.js

**Comment by t638403** [comment]
Not an issue after all
