### ISSUE TITLE
SyntaxError: Invalid regular expression when entering the filter term "*?"

### ISSUE THREAD

**Issue by ret0** [angular-ui/ui-grid#5301]
In the following example: http://jsfiddle.net/ts8h2w94/3/ I get the following stacktrace after entering "*?" as the filter expression. This seems to affect all versions that I tested, including the example on the website ("Complex Example" on http://ui-grid.info/).

```
SyntaxError: Invalid regular expression: /^[\s\S]*??$/: Nothing to repeat
    at RegExp (native)
    at Object.guessCondition (http://ui-grid.info/release/ui-grid-unstable.js:9545:14)
    at Object.setupFilters (http://ui-grid.info/release/ui-grid-unstable.js:9592:45)
    at Object.search (http://ui-grid.info/release/ui-grid-unstable.js:9805:59)
    at Grid.searchRows (http://ui-grid.info/release/ui-grid-unstable.js:5400:24)
    at startProcessor (http://ui-grid.info/release/ui-grid-unstable.js:4894:33)
    at handleProcessedRows (http://ui-grid.info/release/ui-grid-unstable.js:4910:20)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11573:81)
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11573:81)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11659:26
```

This issue appears to be similar to http://stackoverflow.com/questions/29554683/angularjs-ui-utils-highlight-filter-breaks-application-on-search

**Comment by nkoterba** [comment]
👍 Just encountered this on our app as well.  When users put in non-standard regex terms (such as `*?` or `?*`), they get this error.

Looks like ui-grid is trying to guess the condition of the filter based on its value (leading *, trailing *, surrounded by *).

We worked around this by explicitly setting a filter condition for each column. See: http://ui-grid.info/docs/#/tutorial/103_filtering

for examples on how to set conditions on filters.  We do most of our processing on the backend/server-side so the actual value of the front-end filter condition doesn't really matter.  By using a value of `uiGridConstants.filter.CONTAINS` we no longer get the Regex exception and functionality appears to be the same (again because we are doing all our filtering server side).

**Comment by stadler** [comment]
Same issue here.
