### ISSUE TITLE
Getting error `[ngModel:datefmt]` on editing date in grid

### ISSUE THREAD

**Issue by bartvanderwal** [angular-ui/ui-grid#5456]
I'm getting this error in the console the moment I double click a date in a grid to start editing it.
```
Error: [ngModel:datefmt] http://errors.angularjs.org/1.5.6/ngModel/datefmt?p0=1970-01-01T00%3A00%3A00
``` 
See full stacktrace below; but it trails into Angular framework, not into my own code. The date that was displayed, f.i. `2016-01-01` is also not filled displayed or selected in the date picker. So that's probably because of the error, and the error must come from the code that takes the date and tries to fill in the datepicker.

This example on the ui-grid.info site DOES work for some reason, while it is almost identical:
http://ui-grid.info/docs/#/tutorial/201_editable

It doesn't have the problem. I'm using ui-grid v3.1.1, the most recent, and the same as in the example.

These are the colDefs of me and from the example:
```json
{ name: 'trainersinds', displayName: 'Sinds', type: 'date', cellFilter: 'date:"yyyy-MM-dd"', width: '20%' }

{ name: 'registered', displayName: 'Registered', type: 'date', cellFilter: 'date:"yyyy-MM-dd"', width: '20%' }
```

1. The only difference I can discover is that in the example the dates are sent from the backend have an additional timezone in the datestring:
```json
"registered": "1989-07-26T15:52:15+05:00",
```

While those from my own backend do not:
```
"trainerSinds": "1970-01-01T00:00:00",
```

2. Another difference is dat I have more attributes in my `<div ui-grid>` than the example. Namely besides the `ui-grid-edit` I also have `ui-grid-cellNav`, `ui-grid-row-edit`, `ui-grid-pagination` en `ui-grid-resize-columns` heb.

But I've already temporarily changed both 1 and 2 to get it to match up with the example, but my still occurs. Full stack trace:
```
angular.min.js:117 Error: [ngModel:datefmt] http://errors.angularjs.org/1.5.6/ngModel/datefmt?p0=1970-01-01T00%3A00%3A00
    at Error (native)
    at http://localhost:85/bower_components/angular/angular.min.js:6:412
    at Array.<anonymous> (http://localhost:85/bower_components/angular/angular.min.js:179:333)
    at http://localhost:85/bower_components/angular/angular.min.js:286:407
    at m.$digest (http://localhost:85/bower_components/angular/angular.min.js:142:305)
    at http://localhost:85/bower_components/angular/angular.min.js:145:194
    at e (http://localhost:85/bower_components/angular/angular.min.js:45:350)
    at http://localhost:85/bower_components/angular/angular.min.js:48:275
```

**Comment by bartvanderwal** [comment]
I managed to fix this. I hope this can help others.

This issue is caused by Angular, which per v1.3+ requires/assumes fields of type="date" to be a Javascript data (when it has an `ng-model` on it, which apparently ui-grid is doing). So it throws the `[ngModel:datefmt]` exception when it is not. I managed to fix this by simply converting the incoming string to Date using the `new Date()` constructor. After this I actually noticed this is also done in the example I referenced, namelijk in line 83 of app.js:

```
data[i].registered = new Date(data[i].registered);
```

--> **closed**
