### ISSUE TITLE
v4.0.4 and v4.0.3 doesn't support angular < 1.3.0

### ISSUE THREAD

**Issue by wubenhe** [angular-ui/ui-grid#6175]
After v4.0.3 it added $applyAsync, it is only supported in angular 1.3+
Should it upgrade the support list from angular 1.2 - 1.4 to angular 1.3 - 1.4? 

TypeError: $scope.$applyAsync is not a function
    at checkSize (webpack:///./~/angular-ui-grid/ui-grid.js?:3508:22)
    at post (webpack:///./~/angular-ui-grid/ui-grid.js?:3498:11)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:64:293
    at J (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:54:373)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:61:297
    at g (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:47:256)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:46:377
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:48:217
    at w (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:52:29)
    at Object.fn (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.28/angular.min.js:195:438)

**Comment by csimpi** [comment]
Hi, I use Angular 1.5.11 but I still get this error: `TypeError: $scope.$applyAsync is not a function`

 It started when I updated to new angular-ui-grid version. I use bower to install packages.

**Comment by kj-johnson** [comment]
The [changelog](https://github.com/angular-ui/ui-grid/blob/master/CHANGELOG.md) shows that v4.0.0's breaking change is that "UI Grid is no longer compatible with angular versions below 1.4"
