### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jempo** [angular-ui/ui-grid#6851]
Hi, I've this problem with more than 1 result search.

`TypeError: Cannot read property 'name' of undefined
    at Grid.buildColumns (http://localhost:9292/test/bower_components/angular-ui-grid/ui-grid.js:4591:44)
    at Object.columnRefreshCallback [as callback] (http://localhost:9292/test/bower_components/angular-ui-grid/ui-grid.js:4334:10)
    at Grid.<anonymous> (http://localhost:9292/test/bower_components/angular-ui-grid/ui-grid.js:4285:20)
    at Object.forEach (http://localhost:9292/test/bower_components/angular/angular.js:339:20)
    at Grid.callDataChangeCallbacks (http://localhost:9292/test/bower_components/angular-ui-grid/ui-grid.js:4277:13)
    at columnDefsWatchFunction (http://localhost:9292/test/bower_components/angular-ui-grid/ui-grid.js:3303:21)
    at $watchCollectionAction (http://localhost:9292/test/bower_components/angular/angular.js:17699:13)
    at Scope.$digest (http://localhost:9292/test/bower_components/angular/angular.js:17836:23)
    at Scope.$apply (http://localhost:9292/test/bower_components/angular/angular.js:18102:24)
    at done (http://localhost:9292/test/bower_components/angular/angular.js:12082:47) undefined`

debugging the code i've found that `if (self.columns[i + headerOffset].name !== self.options.columnDefs[i].name) {` code search an element that is not present in the array. the sum of `headerOffset` goes 1 over above len of the array.

How can i solve then?

Thanks

**Comment by ProSpartan** [comment]
If I am understanding correctly, you could try `if(undefined !== self.columns[i + headerOffset].name && self.columns[i + headerOffset].name !== self.options.colunDefs[i].name)`

**Comment by jempo** [comment]
yes but the complete code is (in `Grid.buildColumns` function): 
`if (self.columns[i + headerOffset].name !== self.options.columnDefs[i].name) {
          // Replace the one in the cache with the appropriate column
          columnCache[i + headerOffset] = self.getColumn(self.options.columnDefs[i].name);
        }
        else {
          // Otherwise just copy over the one from the initial columns
          columnCache[i + headerOffset] = self.columns[i + headerOffset];
        }`

and also the next element goes to error. But i don't understand why is defined this variable `headerOffset` and who is the functionality.

**Comment by ProSpartan** [comment]
What is it that you are doing when the error occurs? Can you provide any of your code to help?

**Comment by MartijnWelker** [comment]
For me this error was occurring when a column was in the `options.columnDefs` twice, it will be removed from `self.colums` but since the `Math.min` takes `(columDefs-duplicates)+headerOffset` (in my case the lengths were `8` vs `8-1+2`) it will still be more than `self.options.columnDefs.length`, so then it will proceed to go out of bounds because it takes the old columnDefs length.

Instead of doing 
```
var len = Math.min(self.options.columnDefs.length, self.columns.length);
for (i = 0; i < len; i++) {
```

It should do
```
var len = Math.min(self.options.columnDefs.length, (self.columns.length - headerOffset));
for (i = 0; i <= len; i++) {
```

However, doing this the `ngRepeat` used to render the columns will error since both columns have the same columnId, so that has to be changed too.

In the image below you can see `duur:minutes` in the columnDefs twice, but only in the columns once, but `columnDefs.length` is still less than `self.columns.length` because of the added rowHeaderColumns

<img width="992" alt="screen shot 2018-12-10 at 12 56 56" src="https://user-images.githubusercontent.com/6674662/49731347-501c2980-fc7b-11e8-8f48-c5b1813bbc44.png">

**Comment by ankurraiyani** [comment]
@jempo Did you get the solution of this issue?
I am facing this issue right now. I am using version 4.0.2
