### ISSUE TITLE
grunt test:e2e error code 135

### ISSUE THREAD

**Issue by unaccomplished** [angular-ui/ui-grid#6854]
This is my first time writing a bug/issue, so please let me know if I missed anything or posting this incorrectly. In preparation for my first PR, I followed the instructions in https://github.com/angular-ui/ui-grid/blob/master/FIRST_TIMER.md and got to the `grunt test:e2e` command. I'm getting error code 135: 

```
➜  ui-grid git:(master) ✗ grunt test:e2e
Running "connect:testserver" (connect) task
Started connect web server on http://localhost:9999

Running "protractor:singlerun" (protractor) task
[19:28:15] I/launcher - Running 1 instances of WebDriver
[19:28:15] E/local - Error code: 135
[19:28:15] E/local - Error message: No selenium server jar found at /Users/jocelynhsu/Development/ui-grid/node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.11.0.jar. Run 'webdriver-manager update' to download binaries.
[19:28:15] E/local - Error: No selenium server jar found at /Users/jocelynhsu/Development/ui-grid/node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.11.0.jar. Run 'webdriver-manager update' to download binaries.
  at Local.addDefaultBinaryLocs_ (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/built/driverProviders/local.js:44:19)
  at Local.setupDriverEnv (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/built/driverProviders/local.js:105:14)
  at Local.setupEnv (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/built/driverProviders/driverProvider.js:111:34)
  at q.then (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/built/runner.js:335:41)
  at _fulfilled (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:834:54)
  at /Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:863:30
  at Promise.promise.promiseDispatch (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:796:13)
  at /Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:857:14
  at runSingle (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:137:13)
  at flush (/Users/jocelynhsu/Development/ui-grid/node_modules/protractor/node_modules/q/q.js:125:13)
  at process._tickCallback (internal/process/next_tick.js:61:11)
  at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
  at startup (internal/bootstrap/node.js:279:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

[19:28:15] E/launcher - Process exited with error code 135
>>
Warning: Tests failed, protractor exited with code: 135 Use --force to continue.

Aborted due to warnings.


Execution Time (2018-09-22 19:28:13 UTC-7)
loading tasks                     1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 66%
loading grunt-contrib-connect    104ms  ▇▇▇▇▇▇ 5%
connect:testserver                29ms  ▇▇ 2%
loading grunt-protractor-runner   21ms  ▇▇ 1%
protractor:singlerun             493ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 26%
Total 1.9s
```

I tried running `webdriver-manager update`, but the command was not found. Then I googled and tried `node_modules/protractor/bin/webdriver-manager update` (from here: https://github.com/angular/protractor/issues/3268) which gave me this in my terminal:

```
➜  ui-grid git:(master) ✗ node_modules/protractor/bin/webdriver-manager update
[18:59:49] I/config_source - curl -o/Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[18:59:49] I/config_source - curl -o/Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[18:59:49] I/config_source - curl -o/Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[18:59:50] I/update - chromedriver: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/chromedriver_2.42.zip
[18:59:50] I/update - chromedriver: unzipping chromedriver_2.42.zip
[18:59:51] I/update - chromedriver: setting permissions to 0755 for /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/chromedriver_2.42
[18:59:51] I/update - chromedriver: chromedriver_2.42 up to date
[18:59:51] I/update - selenium standalone: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.14.0.jar
[18:59:51] I/update - selenium standalone: selenium-server-standalone-3.14.0.jar up to date
[18:59:52] I/update - geckodriver: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/geckodriver-v0.22.0.tar.gz
[18:59:52] I/update - geckodriver: unzipping geckodriver-v0.22.0.tar.gz
[18:59:53] I/update - geckodriver: setting permissions to 0755 for /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/geckodriver-v0.22.0
[18:59:53] I/update - geckodriver: geckodriver-v0.22.0 up to date
```

However, running `grunt test:e2e` afterwards still gives me the same errors as above. 

I also tried this command `node ./node_modules/grunt-protractor-runner/scripts/webdriver-manager-update` which I found from here: https://github.com/teerapap/grunt-protractor-runner/issues/176. This is what it gave me in my terminal: 

```
➜  ui-grid git:(master) ✗ node ./node_modules/grunt-protractor-runner/scripts/webdriver-manager-update
webdriver-manager path: /Users/jocelynhsu/Development/ui-grid/node_modules/protractor/bin/webdriver-manager
[19:13:18] I/update - chromedriver: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/chromedriver_2.42.zip
[19:13:18] I/update - chromedriver: unzipping chromedriver_2.42.zip
[19:13:18] I/update - chromedriver: setting permissions to 0755 for /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/chromedriver_2.42
[19:13:18] I/update - chromedriver: chromedriver_2.42 up to date
[19:13:19] I/update - selenium standalone: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.14.0.jar
[19:13:19] I/update - selenium standalone: selenium-server-standalone-3.14.0.jar up to date
[19:13:19] I/update - geckodriver: file exists /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/geckodriver-v0.22.0.tar.gz
[19:13:19] I/update - geckodriver: unzipping geckodriver-v0.22.0.tar.gz
[19:13:19] I/update - geckodriver: setting permissions to 0755 for /Users/jocelynhsu/Development/ui-grid/node_modules/webdriver-manager/selenium/geckodriver-v0.22.0
[19:13:19] I/update - geckodriver: geckodriver-v0.22.0 up to date
```

Running `grunt test:e2e` afterwards still results in the same errors I posted above.

I suspect the error is because I have a different version of `selenium-server-standalone-3.14.0.jar` than the e2e test is looking for (`selenium-server-standalone-3.11.0.jar`). I couldn't find any similar bugs already reported or any documentation about this error. I am working in OS X 10.11.6. I cloned the project only a week ago, so it should be the latest version of the grid.

**Comment by rakhiedwin** [comment]
I am also facing a similar kind of issue..While trying to run my test it is exiting with error code 135

` Error code: 135
[11:50:19] E/local - Error message: No selenium server jar found at C:\Repo\theseus-qa-e2e-tests-simplified\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.8.1.jar. Run 'webdriver-manager update' to download binaries.
[11:50:19] E/local - Error: No selenium server jar found at C:\Repo\theseus-qa-e2e-tests-simplified\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.8.1.jar. Run 'webdriver-manager update' to download binaries.
`
As per the error when I try to update webdriver.It is giving the below error
`events.js:187
      throw er; // Unhandled 'error' event
      `

`Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com
`
` errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'chromedriver.storage.googleapis.com'
`

Tried many ways going through many similar kind of issues,but still it is the same

**Comment by orneryd** [comment]
Thanks for contributing! This repository has been transferred, and we're preparing the new 5.x release. We're closing older issues and pull requests as part of the reset. Please join us on Discord to follow the work or continue the conversation: https://discord.gg/Baz4w8ZWN
